MinPro180.MVC/Controllers/ClassController.cs
using MinPro180.Repository;
using MinPro180.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MinPro180.MVC.Controllers
{
    [Authorize]
    public class ClassController : Controller
    {
        // GET: Class
        public ActionResult Index()
        {
            return View(ClassRepo.All());
        }

        public ActionResult List(ClassViewModel entity)
        {
            
            return PartialView("_List", ClassRepo.All());
        }
    }
}

MinPro180.MVC/Controllers/TestController.cs
using MinPro180.Repository;
using MinPro180.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MinPro180.MVC.Controllers
{
    [Authorize]
    public class TestController : Controller
    {
        // GET: Test
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            return PartialView("_List", TestRepo.All());
        }

        public ActionResult Search(string code)
        {
            List<TestViewModel> item = TestRepo.All(code);
            return PartialView("_List", item);
        }

        public ActionResult Create()
        {
            return PartialView("_Create");
        }

        [HttpPost]
        public ActionResult Create(TestViewModel model)
        {
            var userid = (long)Session["userid"];
            ResponResultViewModel result = TestRepo.Update(model, userid);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Update(int id)
        {
            return PartialView("_Update", TestRepo.Get(id));
        }

        [HttpPost]
        public ActionResult Update(TestViewModel model)
        {
            var userid = (long)Session["userid"];
            ResponResultViewModel result = TestRepo.Update(model,userid);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Deact(int id)
        {
            return PartialView("_Deact", TestRepo.Get(id));
        }

        [HttpPost]
        public ActionResult Deact(TestViewModel model)
        {
            var userid = (long)Session["userid"];
            ResponResultViewModel result = TestRepo.Deact(model,userid);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

MinPro180.MVC/Views/Class/Index.cshtml
@{
    ViewBag.Title = "Class";
}
<div class="panel panel-default">
    @*<div class="panel-heading">
            <div class="row">
                <div class="col-lg-12">
                    <button type="button" id="btn-new" class="btn btn-success btn-sm">Create New</button>
                </div>
            </div>
        </div>*@
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-12" id="table-list">
                <h3>Loading...</h3>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            GetList();
        });

        function GetList() {
            $.ajax({
                url: '@Url.Action("List","Class")',
                type: 'get',
                success: function (result) {
                    $("#table-list").html(result);
                },
                error: function (err) {
                    $("#table-list").html(err);
                }
            });
        }

        @*$("#table-list").on("click", ".btn-edit", function () {
            $.ajax({
                url: '@Url.Action("Update", "Class")',
                type: 'get',
                data: { id: $(this).attr("data-id") },
                success: function (result) {
                    $(".modal-title").html("Edit Test Data");
                    $(".modal-body").html(result);
                    $(".modal").modal("show");
                },
                error: function (err) {
                    alert(err);
                }
            });
        });

        $("#table-list").on("click", ".btn-deact", function () {
            $.ajax({
                url: '@Url.Action("Deact", "Test")',
                type: 'get',
                data: { id: $(this).attr("data-id") },
                success: function (result) {
                    $(".modal-title").html("Deactivate Test Data");
                    $(".modal-body").html(result);
                    $(".modal").modal("show");
                },
                error: function (err) {
                    alert(err);
                }
            });
        });*@
    </script>
}

MinPro180.MVC/Views/Class/_List.cshtml
@model IEnumerable<MinPro180.ViewModel.ClassViewModel>

<table class="table">
    <tr>
        <td colspan="2">@Html.TextBox("name", "", new { @class = "form-control", @placeholder = "Search by Batch" })</td>
        <td>
            <button type="button" id="btn-new" class="btn btn-success btn-sm">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
            </button>
        </td>
    </tr>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.batchtech)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.bioname)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.batchtech)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.bioname)
            </td>
            <td>
                <button type="button" class="btn btn-warning btn-deact" data-id="@item.id" title="Deactive">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                </button>
            </td>
        </tr>
    }

</table>