MinPro180.MVC/Controllers/MonitoringController.cs
using MinPro180.Repository;
using MinPro180.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MinPro180.MVC.Controllers
{
    [Authorize]
    public class MonitoringController : Controller
    {
        // GET: Monitoring
        public ActionResult Index()
		{

			return View();
		}

		public ActionResult List(string search)
		{
			return PartialView("_List", MonitoringRepo.All(search));
		}
		public ActionResult Create()
		{
			ViewBag.Biodatalist = new SelectList(BiodataRepo.All(""), "id", "name");
			return PartialView("_Create");
		}
		[HttpPost]
		public ActionResult Create(MonitoringViewModel model)
		{
            var userid = (long)Session["userid"];
            ResponResultViewModel result = MonitoringRepo.Update(model,userid);
			return Json(new
			{
				success = result.Success,
				message = result.Message,
				entity = result.Entity
			}, JsonRequestBehavior.AllowGet);
		}
		public ActionResult Edit(int id)
		{
			ViewBag.Biodatalist = new SelectList(BiodataRepo.All(""), "id", "name");
			return PartialView("_Edit", MonitoringRepo.GetMonitoring(id));
		}

		[HttpPost]
		public ActionResult Edit(MonitoringViewModel model)
		{
            var userid = (long)Session["userid"];
            ResponResultViewModel result = MonitoringRepo.Update(model,userid);
			return Json(new
			{
				success = result.Success,
				message = result.Message,
				entity = result.Entity
			}, JsonRequestBehavior.AllowGet);
		}
		public ActionResult Placement(int id)
		{
			return PartialView("_Placement", MonitoringRepo.GetPlacement(id));
		}

		[HttpPost]
		public ActionResult Placement(MonitoringViewModel model)
		{
            var userid = (long)Session["userid"];
            ResponResultViewModel result = MonitoringRepo.CreatePlacement(model,userid);
			return Json(new
			{
				success = result.Success,
				message = result.Message,
				entity = result.Entity
			}, JsonRequestBehavior.AllowGet);
		}
		public ActionResult Delete(int id)
		{
			return PartialView("_IsDelete", MonitoringRepo.GetMonitoring(id));
		}

		[HttpPost]
		public ActionResult Delete(MonitoringViewModel model)
		{
            var userid = (long)Session["userid"];
            ResponResultViewModel result = MonitoringRepo.Is_Delete(model,userid);
			return Json(new
			{
				success = result.Success,
				message = result.Message,
				entity = result.Entity
			}, JsonRequestBehavior.AllowGet);
		}
	}
}

MinPro180.MVC/Views/Monitoring/Index.cshtml
@{
    ViewBag.Title = "Idle Monitoring";
}
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-lg-3">
                <div class="input-group">
                    <input type="text" class="form-control" id="txt" placeholder="Search By Name" />
                </div><!-- /input-group -->
            </div><!-- /.col-lg-6 -->
            <div class="col-lg-2 col-lg-offset-5">
                <button type="button" class="btn btn-warning btn-new">
                    <span class="glyphicon glyphicon-plus"></span>
                </button>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-12" id="table-list">
                <h1>Loading...</h1>
                <h8>List is here.. :)</h8>
            </div>
        </div>
    </div>
</div>

@* Modal *@
<div class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background-color: #ffad5b">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Create</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            GetList();
        });


        function GetList(){
            $.ajax({
                url: '@Url.Action("List","Monitoring")',
				type: 'get',
				data: { search: $("#txt").val() },
                success: function (result) {
                    $("#table-list").html(result);
                },
                error: function (err) {
                    $("#table-list").html(err);
                }
            });
		}

	  $("#txt").keyup(function () {
      $.ajax({
            url: '@Url.Action("List", "Monitoring")',
            type: 'get',
            data: { search: $("#txt").val()},
            success: function (result) {
             GetList();
            }
         });
		})

		 $('.btn-new').click(function () {
         $.ajax({
               url: '@Url.Action("Create","Monitoring")',
               type: 'get',
               success: function (result) {
                    $(".modal-title").html("Add Idle")
                    $(".modal-body").html(result);
                    $(".modal").modal("show")
                },
                error: function (err) {
                    alert(err);
                }
            });
		});

    </script>
}

MinPro180.MVC/Views/Monitoring/_Create.cshtml
	@model MinPro180.ViewModel.MonitoringViewModel

@using (Html.BeginForm("Create", "Monitoring", FormMethod.Post, new { id = "create-form", name = "create-form" }))
{
	

<div class="form-horizontal">

	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
	@Html.HiddenFor(x=>x.placement_date)
	<div class="form-group">
		
		<div class="col-md-10">
			@Html.DropDownListFor(model => model.biodata_id,(IEnumerable<SelectListItem>)
			 ViewBag.Biodatalist, "--Select Name--", new { @class = "form-control" })
			@Html.ValidationMessageFor(model => model.biodata_id, "", new { @class = "text-danger" })
		</div>
	</div>
	<div class="form-group">

		<div class="col-md-12">
			@Html.EditorFor(model => model.idle_date, new { htmlAttributes = new { @class = "form-control" }, @placeholder = "Idle Date" })
			@Html.ValidationMessageFor(model => model.idle_date, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">

		<div class="col-md-12">
			@Html.EditorFor(model => model.last_project, new { htmlAttributes = new { @class = "form-control", @placeholder = "Last project" } })
			@Html.ValidationMessageFor(model => model.last_project, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">

		<div class="col-md-12">
			@Html.EditorFor(model => model.idle_reason, new { htmlAttributes = new { @class = "form-control", @placeholder = "Idle Reason" } })
			@Html.ValidationMessageFor(model => model.idle_reason, "", new { @class = "text-danger" })
		</div>
	</div>


	<div class="form-group">
		<div class="col-md-offset-2 col-md-10">
			<input type="submit" value="Save" class="btn btn-warning" />
			<input type="button" value="Cancel" class="btn btn-default" data-dismiss="modal" />
		</div>
	</div>
</div>
}

@Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript">
    $("#create-form").submit(function () {
        //alert($(this).serialize());
        $.ajax({
			url: '@Url.Action("Create","Monitoring")',
			type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("Data Successfully Added");
                    $(".modal").modal("hide");
                    GetList();
                } else {
                    alert("Error!." + result.message)
                }
            }
        });
        return false;
    });

</script>

MinPro180.MVC/Views/Monitoring/_Edit.cshtml
@model MinPro180.ViewModel.MonitoringViewModel

@using (Html.BeginForm("Edit", "Monitoring", FormMethod.Post, new { id = "edit-form", name = "edit-form" }))

{
	
	@Html.HiddenFor(model=>model.id)

	<div class="form-horizontal">

		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		@Html.HiddenFor(model => model.id)

		<div class="form-group">

			<div class="col-md-10">
				@Html.DropDownListFor(model => model.biodata_id,(IEnumerable<SelectListItem>)
				 ViewBag.Biodatalist, "--Select Name--", new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.biodata_id, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">

			<div class="col-md-12">
				@Html.EditorFor(model => model.idle_date, new { htmlAttributes = new { @class = "form-control" }, @placeholder = "Idle Date" })
				@Html.ValidationMessageFor(model => model.idle_date, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">

			<div class="col-md-12">
				@Html.EditorFor(model => model.last_project, new { htmlAttributes = new { @class = "form-control", @placeholder = "Last project" } })
				@Html.ValidationMessageFor(model => model.last_project, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">

			<div class="col-md-12">
				@Html.EditorFor(model => model.idle_reason, new { htmlAttributes = new { @class = "form-control", @placeholder = "Idle Reason" } })
				@Html.ValidationMessageFor(model => model.idle_reason, "", new { @class = "text-danger" })
			</div>
		</div>


		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Save" class="btn btn-warning" />
				<input type="button" value="Cancel" class="btn btn-default" data-dismiss="modal" />
			</div>
		</div>
	</div>
}

@Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript">
    $("#edit-form").submit(function () {
        //alert($(this).serialize());
        $.ajax({
			url: '@Url.Action("Edit","Monitoring")',
			type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("Data Successfully Updated");
                    $(".modal").modal("hide");
                    GetList();
                } else {
                    alert("Error!." + result.message)
                }
            }
        });
        return false;
    });

</script>

MinPro180.MVC/Views/Monitoring/_IsDelete.cshtml
@model MinPro180.ViewModel.MonitoringViewModel


@using (Html.BeginForm("Delete", "Monitoring", FormMethod.Post, new { id = "delete-form", name = "delete-form" }))
{
	
	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
	@Html.HiddenFor(model => model.id)

	<h5>Are you sure you want to delete this data?</h5>

	<div class="form-horizontal">
		<div class="form-group">
			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					<input type="submit" value="Delete" class="btn btn-warning" />
					<input type="button" value="Cancel" class="btn btn-default" data-dismiss="modal" />
				</div>
			</div>
		</div>
	</div>
}

@Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript">
    $("#delete-form").submit(function () {
        //alert($(this).serialize());
        $.ajax({
			url: '@Url.Action("Delete","Monitoring")',
			type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("Data Successfully Deleted!");
                    $(".modal").modal("hide");
                    GetList();
                } else {
                    alert("Error!." + result.message)
                }
            }
        });
        return false;
    });
</script>

MinPro180.MVC/Views/Monitoring/_List.cshtml
@model IEnumerable<MinPro180.ViewModel.MonitoringViewModel>


<table class="table">

	<tr>
		<th>
			@Html.DisplayNameFor(model => model.biodata_id)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.idle_date)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.placement_date)
		</th>

		<th></th>
	</tr>

	@foreach (var item in Model)
	{
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.bio_name)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.idle_date)
			</td>

			<td>
				@if (String.IsNullOrEmpty(item.placement_at))
				{

					
				}
				 else
				{
					@Html.DisplayFor(modelItem => item.placement_date);
				}
				
			</td>


			<td>

				<div class="dropdown">
					<button class="btn btn-warning dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
						<span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
						@*<span class="caret"></span>*@
					</button>
					<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
						<li class="li-Edit" data-id="@item.id"><a href="#">Edit</a></li>
						<li class="li-Place" data-id="@item.id"><a href="#">Placement</a></li>
						<li class="li-Delete" data-id="@item.id"><a href="#">Delete</a></li>
					</ul>
				</div>
			</td>
		</tr>
	}

</table>
<script type="text/javascript">

 

	 $(".li-Edit").click(function () {
        $.ajax({
            url: '@Url.Action("Edit", "Monitoring")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $(".modal-title").html("Edit Idle");
                $(".modal-body").html(result);
                $(".modal").modal("show");

            }
        });

	})
		 $(".li-Place").click(function () {
        $.ajax({
            url: '@Url.Action("Placement", "Monitoring")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $(".modal-title").html("Input Placement");
                $(".modal-body").html(result);
                $(".modal").modal("show");

            }
        });

    })
	 $(".li-Delete").click(function () {
        $.ajax({
            url: '@Url.Action("Delete", "Monitoring")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $(".modal-title").html("Delete Idle");
                $(".modal-body").html(result);
                $(".modal").modal("show");

            }
        });

    })

</script>

MinPro180.MVC/Views/Monitoring/_Placement.cshtml
@model MinPro180.ViewModel.MonitoringViewModel


@using (Html.BeginForm("Placement", "Monitoring", FormMethod.Post, new { id = "place-form", name = "place-form" }))
{
	<div class="form-horizontal">
	
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		@Html.HiddenFor(model => model.id)
		@Html.HiddenFor(model=>model.biodata_id)
		@Html.HiddenFor(model=>model.idle_date)

		<div class="form-group">
			<div class="col-md-12">
				@Html.EditorFor(model => model.placement_date, new { htmlAttributes = new { @class = "form-control", @placeholder = "Placement Date" } })
				@Html.ValidationMessageFor(model => model.placement_date, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-12">
				@Html.EditorFor(model => model.placement_at, new { htmlAttributes = new { @class = "form-control", @placeholder = "Placement at" } })
				@Html.ValidationMessageFor(model => model.placement_at, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">

			<div class="col-md-12">
				@Html.TextAreaFor(model => model.notes, 6, 40, new { @class = "form-control", @placeholder = "Notes" })
				@Html.ValidationMessageFor(model => model.notes, "", new { @class = "text-danger" })
			</div>
		</div>


		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Save" class="btn btn-warning" />
				<input type="button" value="Cancel" class="btn btn-default" data-dismiss="modal" />
			</div>
		</div>
	</div>
}

@Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript">
    $("#place-form").submit(function () {
        //alert($(this).serialize());
        $.ajax({
			url: '@Url.Action("Placement","Monitoring")',
			type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("Data Successfully Added !");
                    $(".modal").modal("hide");
                    GetList();
                } else {
                    alert("Error!." + result.message)
                }
            }
        });
        return false;
    });

</script>