MinPro180.MVC/Controllers/MenuAccessController.cs
using MinPro180.Repository;
using MinPro180.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MinPro180.MVC.Controllers
{
    [Authorize]
    public class MenuAccessController : Controller
    {
        // GET: MenuAccess
        public ActionResult Index()
        {
            ViewBag.RoleList = new SelectList(RoleRepo.All(null), "id", "name");
            return View(MenuAccessRepo.All());
        }
        public ActionResult List()
        {
            return PartialView("_List", MenuAccessRepo.All());
        }
        public ActionResult search(long? key)
        {
            List<MenuAccessViewModel> result = MenuAccessRepo.search(key);
            return PartialView("_ListMenuAccess", result);
        }
        public ActionResult Create()
        {
            ViewBag.RoleList = new SelectList(RoleRepo.All(null), "id", "name");
            ViewBag.MenuList = new SelectList(MenuRepo.All(null), "id", "title");
            return PartialView("_Create");
        }
        [HttpPost]
        public ActionResult Create(MenuAccessViewModel model)
        {
            var userid = (long)Session["userid"];
            ResponResultViewModel result = MenuAccessRepo.Update(model,userid);
            return Json(new { success = result.Success, message = result.Message, entity = result.Entity }, JsonRequestBehavior.AllowGet);
        }
       public ActionResult Delete(long id)
        {
            return PartialView("_Delete", MenuAccessRepo.GetId(id));
        }
        [HttpPost]
        public ActionResult Delete(MenuAccessViewModel model)
        {
            ResponResultViewModel result = MenuAccessRepo.Delete(model.id);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
    
        public ActionResult RoleList()
        {
            return PartialView("_RoleList", RoleRepo.All(null));
        }
    }
}

MinPro180.MVC/Views/MenuAccess/Index.cshtml
@{
    ViewBag.Title = "Menu Access";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            @*<h3 style="color: red; font-family: 'Bookman Old Style'">Data Menu Access</h3>*@
            <div class="col-lg-3" id="role-list">
                @Html.DropDownList("role_id", (IEnumerable<SelectListItem>)ViewBag.RoleList, "-- Select Role --", new { @class = "form-control" })
            </div>
            
            <div class="col-lg-1 pull-right">
                <button type="button" id="btn-new" class="btn btn-warning btn-sm"><span class="glyphicon glyphicon-plus"></span></button>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-12" id="table-list">
                <h3>Loading...</h3>
            </div>
        </div>
    </div>
</div>

@*--------------modal------------------*@

<div class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background-color: #ffad5b; font-family: 'Bookman Old Style'"">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
@*--------------JS------------------*@

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            GetList();

        });

        $("#btn-new").click(function () {
            $.ajax({
                url: '@Url.Action("Create", "MenuAccess")',
                type: 'get',
                success: function (result) {
                    $(".modal-title").html("Create New Menu Access");
                    $(".modal-body").html(result);
                    $(".modal").modal("show");
                },
                error: function (err) {
                    alert(err);
                }
            });
        });

        function GetList() {
            $.ajax({
                url: '@Url.Action("List", "MenuAccess")',
                type: 'get',
                success: function (result) {
                    $("#table-list").html(result);
                }, error(err) {
                    $("#table-list").html(err);
                }
            });
        }

        $(".btn-src").click(function () {
            $.ajax({
                url: '@Url.Action("search", "MenuAccess")',
                type: 'get',
                data: {key: $("#role_id").val()},
                success: function (result) {
                    $("#table-list").html(result);
                }
            });
        })

        $("#role_id").change(function () {
            if ($(this).val() == "") {
                $.ajax({
                    url: '@Url.Action("List", "MenuAccess")',
                    type: 'get',
                    success: function (result) {
                        $("#table-list").html(result);
                    }
                });
            }
            if ($(this).val()) {
                $.ajax({
                    url: '@Url.Action("search", "MenuAccess")',
                    type: 'get',
                    data: { key: $("#role_id").val() },
                    success: function (result) {
                        $("#table-list").html(result);
                    }
                });
            }
        });
    </script>

}

MinPro180.MVC/Views/MenuAccess/_Create.cshtml
@model MinPro180.ViewModel.MenuAccessViewModel


@using (Html.BeginForm("Create", "MenuAccess", FormMethod.Post, new { id = "create-form", name = "create-form" }))
{
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.menu_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               @Html.DropDownListFor(model => model.menu_id, (IEnumerable<SelectListItem>)ViewBag.MenuList, "-- Select List --", new { @class = "form-control" })
                @*@Html.EditorFor(model => model.menu_id, new { @class= "form-control"})*@
                @Html.ValidationMessageFor(model => model.menu_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.role_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.role_id, (IEnumerable<SelectListItem>)ViewBag.RoleList, "-- Select Role --", new { @class = "form-control"})
                @Html.ValidationMessageFor(model => model.role_id, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="btn-group btn-group-sm">
                    <input type="submit" value="Save" class="btn btn-warning" />
                    <input type="button" value="Cancel" class="btn btn-default" data-dismiss="modal" />
                </div>
            </div>
        </div>
    </div>
}




    @Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript">
    $("#create-form").submit(function (result) {
        $.ajax({
            url: '@Url.Action("Create", "MenuAccess")',
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("Data Successfully Added");
                    $(".modal").modal("hide");
                    GetList();
                } else {
                    alert("Error .." + result.message);
                }
            }
        });
        return false;
    });
</script>

MinPro180.MVC/Views/MenuAccess/_Delete.cshtml
@model MinPro180.ViewModel.MenuAccessViewModel

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.menu_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.menu_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.role_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.role_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>


    </dl>

    @using (Html.BeginForm("Delete", "MenuAccess", FormMethod.Post, new { id = "delete-form", name = "delete-form" }))
    {
        
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            <div class="form-actions no-color">
                <div class="btn-group btn-group-sm">
                    <input type="submit" value="Delete" class="btn btn-danger" />
                    <input type="button" value="Cancel" class="btn btn-default" data-dismiss="modal" />
                </div>
            </div>
        </div>

    }
</div>

<script type="text/javascript">
    $("#delete-form").submit(function () {
        $.ajax({
            url: '@Url.Action("Delete","MenuAccess")',
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("Data Successfully Deleted");
                    $(".modal").modal("hide");
                    GetList();
                } else {
                    alert("error .." + result.message);
                }
            }
        });
        return false;
    });
</script>

MinPro180.MVC/Views/MenuAccess/_List.cshtml
@model IEnumerable<MinPro180.ViewModel.MenuAccessViewModel>

<p>

</p>
<table class="table">
    
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.role_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.menu_id)
        </th>


        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.title)
            </td>


            <td>
                <div class="dropdown">
                    <button class="btn btn-warning dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
                        @*<span class="caret"></span>*@
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        <li class="li-delete" data-id="@item.id"><a href="#">Delete</a></li>
                    </ul>
                </div>
            </td>
        </tr>
    }

</table>

<script type="text/javascript">
    $(".li-delete").click(function (result) {
        $.ajax({
            url: '@Url.Action("Delete", "MenuAccess")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $(".modal-title").html("Delete Menu Access");
                $(".modal-body").html(result);
                $(".modal").modal("show");
            }
        });
    });
</script>

MinPro180.MVC/Views/MenuAccess/_ListMenuAccess.cshtml
@model IEnumerable<MinPro180.ViewModel.MenuAccessViewModel>

<table class="table" id="_table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.role_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.menu_id)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
      
        <td>
            <div class="dropdown">
                <button class="btn btn-warning dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
                    @*<span class="caret"></span>*@
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                    <li class="li-delete" data-id="@item.id"><a href="#">Delete</a></li>
                </ul>
            </div>
        </td>
    </tr>
}

</table>