MinPro180.MVC/Controllers/IdleController.cs
using MinPro180.Repository;
using MinPro180.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MinPro180.MVC.Controllers
{
    [Authorize]
    public class IdleController : Controller
    {
        // GET: Idle
        public ActionResult Index()
        {
            return View(IdleRepo.All());
        }
        public ActionResult List()
        {
            return PartialView("_List", IdleRepo.All());
        }
        public ActionResult search(string key)
        {
            List<IdleViewModel> result = IdleRepo.search(key);
            return PartialView("_ListIdle", result);
        }
        public ActionResult Create()
        {
            ViewBag.CategoryList = new SelectList(CategoryRepo.All(), "id", "code");
            return PartialView("_Create");
        }
        [HttpPost]
        public ActionResult Create(IdleViewModel model)
        {
            var userid = (long)Session["userid"];
            ResponResultViewModel result = IdleRepo.Update(model,userid);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Edit(long id)
        {
            ViewBag.CategoryList = new SelectList(CategoryRepo.All(), "id", "code");
            return PartialView("_Edit", IdleRepo.GetId(id));
        }
        [HttpPost]
        public ActionResult Edit(IdleViewModel model)
        {
            var userid = (long)Session["userid"];
            ResponResultViewModel result = IdleRepo.Update(model,userid);
            return Json(new {success = result.Success, message =result.Message, entity =result.Entity }, JsonRequestBehavior.AllowGet);

        }
        public ActionResult Delete(long id)
        {
            return PartialView("_Delete", IdleRepo.GetId(id));
        }
        [HttpPost]
        public ActionResult Delete(IdleViewModel model)
        {
            var userid = (long)Session["userid"];
            ResponResultViewModel result = IdleRepo.isdelete(model,userid);
            return Json(new { success = result.Success, message = result.Message, entity = result.Entity }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ispublish(long id)
        {
            return PartialView("publish", IdleRepo.GetId(id));
        }
        [HttpPost]
        public ActionResult ispublish(IdleViewModel model)
        {
            var userid = (long)Session["userid"];
            ResponResultViewModel result = IdleRepo.ispublish(model,userid);
            return Json(new { success = result.Success, message = result.Message, entity = result.Entity }, JsonRequestBehavior.AllowGet);
        }
    }
}

MinPro180.MVC/Views/Idle/Index.cshtml
@{
    ViewBag.Title = "Idle News";
}

    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-lg-3">
                    <input type="text" id="txt-search" placeholder="Search by title" class="form-control" />
                </div>
      
                <div class="col-lg-1 pull-right">
                    <button type="button" id="btn-new" class="btn btn-warning btn-sm"><span class="glyphicon glyphicon-plus"></span></button>
                </div>

            </div>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-12" id="table-list">
                    <h3>Loading...</h3>
                </div>
            </div>
        </div>
    </div>


@*--------------modal------------------*@

<div class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background-color: #ffad5b; font-family: 'Bookman Old Style'"">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@*--------------JS------------------*@

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            GetList();
        });

        $("#btn-new").click(function () {
            $.ajax({
                url: '@Url.Action("Create", "Idle")',
                type: 'get',
                success: function (result) {
                    $(".modal-title").html("Create New Idle News");
                    $(".modal-body").html(result);
                    $(".modal").modal("show");
                },
                error: function (err) {
                    alert(err);
                }
            });
        });

        function GetList() {
            $.ajax({
                url: '@Url.Action("List", "Idle")',
                type: 'get',
                success: function (result) {
                    $("#table-list").html(result);
                }, error(err) {
                    $("#table-list").html(err);
                }
            });
        }

        $(".btn-src").click(function () {
            $.ajax({
                url: '@Url.Action("search", "Idle")',
                type: 'get',
                data: { key: $("#txt-search").val() },
                success: function (result) {
                    $("#_table").html(result);
                }
            });
        })
        $("#txt-search").keyup(function () {
            if ($(this).val() == "") {
                $.ajax({
                    url: '@Url.Action("List", "Idle")',
                    type: 'get',
                    success: function (result) {
                        $("#table-list").html(result);
                    }
                });
            }
            if ($(this).val()) {
                $.ajax({
                    url: '@Url.Action("search", "Idle")',
                    type: 'get',
                    data: { key: $("#txt-search").val() },
                    success: function (result) {
                        $("#table-list").html(result);
                    }
                });
            }
        });
</script>

    }

MinPro180.MVC/Views/Idle/_Create.cshtml
@model MinPro180.ViewModel.IdleViewModel


@using (Html.BeginForm("Create", "Idle", FormMethod.Post, new { id = "create-form", name = "create-form" }))
{

    <div class="form-horizontal">

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.category_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.category_id, (IEnumerable<SelectListItem>)ViewBag.CategoryList, "-- Select List --", new { @class = "form-control"})
                @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="btn-group btn-group-sm">
                    <input type="submit" value="Save" class="btn btn-warning" />
                    <input type="button" value="Cancel" class="btn btn-default" data-dismiss="modal" />
                </div>
            </div>
        </div>
    </div>
}

    @Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript">
    $("#create-form").submit(function () {
        $.ajax({
            url: '@Url.Action("Create", "Idle")',
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("save Success Name : " + result.entity.content);
                    $(".modal").modal("hide");
                    GetList();
                } else {
                    alert("Errorr .." + result.message);
                }
            }
        });
        return false;
    });
</script>

MinPro180.MVC/Views/Idle/_Delete.cshtml
@model MinPro180.ViewModel.IdleViewModel


@using (Html.BeginForm("Delete", "Idle", FormMethod.Post, new { id = "delete-form", name = "delete-form" }))
{
    

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.category_id, htmlAttributes: new { @class = "control-label col-md-2", @readonly = "readonly" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.category_id, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.content, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.content, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="btn-group btn-group-sm">
                    <input type="submit" value="Delete" class="btn btn-danger" />
                    <input type="button" value="Cancel" class="btn btn-default" data-dismiss="modal" />
                </div>
            </div>
        </div>
    </div>
}



@Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript">
    $("#delete-form").submit(function () {
        $.ajax({
            url: '@Url.Action("Delete", "Idle")',
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("Delete Success");
                    $(".modal").modal("hide");
                    GetList();
                } else {
                    alert("error " + result.message);
                }
            }
        });
        return false;
    });
</script>

MinPro180.MVC/Views/Idle/_Edit.cshtml
@model MinPro180.ViewModel.IdleViewModel


@using (Html.BeginForm("Edit", "Idle", FormMethod.Post, new { id="edit-form", name="edit-form"}))
{
       
    <div class="form-horizontal">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.category_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.category_id, (IEnumerable<SelectListItem>)ViewBag.CategoryList, "-- Select List --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.content, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="btn-group btn-group-sm">
                    <input type="submit" value="Save" class="btn btn-warning" />
                    <input type="button" value="Cancel" class="btn btn-default" data-dismiss="modal" />
                </div>
            </div>
        </div>
    </div>
}


    @Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript">
    $("#edit-form").submit(function () {
        $.ajax({
            url: '@Url.Action("Edit", "Idle")',
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("save successfull ");
                    $(".modal").modal("hide");
                    GetList();
                } else {
                    alert("Error .." + result.message);
                }
            }
        });
        return false;
    });
</script>

MinPro180.MVC/Views/Idle/_List.cshtml
@model IEnumerable<MinPro180.ViewModel.IdleViewModel>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.category)
        </th>
        
        
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.category)
        </td> 
        <td>
            <div class="dropdown">
                <button class="btn btn-warning dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
                    @*<span class="caret"></span>*@
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                    <li class="li-delete" data-id="@item.id"><a href="#">Delete</a></li>
                    <li class="li-edit" data-id="@item.id"><a href="#">Edit</a></li>
                    <li class="li-publish" data-id="@item.id"><a href="#">Publish</a></li>
                </ul>
            </div>
            
        </td>
    </tr>
}

</table>

<script type="text/javascript">
    $(".li-edit").click(function (result) {
        $.ajax({
            url: '@Url.Action("Edit", "Idle")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $(".modal-title").html("Edit Idle News");
                $(".modal-body").html(result);
                $(".modal").modal("show");

            }
        });
    });

    $(".li-delete").click(function (result) {
        $.ajax({
            url: '@Url.Action("Delete", "Idle")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $(".modal-title").html("Delete Idle News");
                $(".modal-body").html(result);
                $(".modal").modal("show");
            }
        });
    });
    $(".li-publish").click(function (result) {
        $.ajax({
            url: '@Url.Action("ispublish", "Idle")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $(".modal-title").html("Publish Idle News");
                $(".modal-body").html(result);
                $(".modal").modal("show");
            }
        })
    });
</script>

MinPro180.MVC/Views/Idle/_ListIdle.cshtml
@model IEnumerable<MinPro180.ViewModel.IdleViewModel>

<table class="table" id="_table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.category_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.category_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        
        <td>
            <div class="dropdown">
                <button class="btn btn-warning dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
                    @*<span class="caret"></span>*@
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                    <li class="li-delete" data-id="@item.id"><a href="#">Delete</a></li>
                    <li class="li-edit" data-id="@item.id"><a href="#">Edit</a></li>
                    <li class="li-publish" data-id="@item.id"><a href="#">Publish</a></li>
                </ul>
            </div>
        </td>
    </tr>
}

</table>

<script type="text/javascript">

   
</script>

MinPro180.MVC/Views/Idle/publish.cshtml
@model MinPro180.ViewModel.IdleViewModel


@using (Html.BeginForm("Publish", "Idle", FormMethod.Post, new { id = "publish-form", name = "publish-form" }))
{
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.category_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.category_id, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.content, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.content, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="btn-group btn-group-sm">
                    <input type="submit" value="Publish" class="btn btn-info" />
                    <input type="button" value="Cancel" class="btn btn-default" data-dismiss="modal" />
                </div>
            </div>
        </div>
    </div>
}


    @Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript">
    $("#publish-form").submit(function () {
        $.ajax({
            url: '@Url.Action("ispublish", "Idle")',
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("Publish success");
                    $(".modal").modal("hide");
                    GetList();
                } else {
                    alert("Error " + result.message);
                }
            }
        });
        return false;
    });
</script>